// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFynL12u7_8r2kPA6JoxPNfcAn5IPRgVU',
    appId: '1:863822323375:web:8de12f03fe5d179ec23e5a',
    messagingSenderId: '863822323375',
    projectId: 'fir-setup-4d5ce',
    authDomain: 'fir-setup-4d5ce.firebaseapp.com',
    storageBucket: 'fir-setup-4d5ce.firebasestorage.app',
    measurementId: 'G-Y6M3BP7YT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU1H2xDW8xy8iJo2hzUdOForLyQvP00xo',
    appId: '1:863822323375:android:7ef5986a825ac0a2c23e5a',
    messagingSenderId: '863822323375',
    projectId: 'fir-setup-4d5ce',
    storageBucket: 'fir-setup-4d5ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzHQlx7U-S5q35puGb0eTECKC0xKvjJiI',
    appId: '1:863822323375:ios:f67faedcb12f431cc23e5a',
    messagingSenderId: '863822323375',
    projectId: 'fir-setup-4d5ce',
    storageBucket: 'fir-setup-4d5ce.firebasestorage.app',
    iosBundleId: 'com.example.arellanoAdvmobprog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzHQlx7U-S5q35puGb0eTECKC0xKvjJiI',
    appId: '1:863822323375:ios:f67faedcb12f431cc23e5a',
    messagingSenderId: '863822323375',
    projectId: 'fir-setup-4d5ce',
    storageBucket: 'fir-setup-4d5ce.firebasestorage.app',
    iosBundleId: 'com.example.arellanoAdvmobprog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFynL12u7_8r2kPA6JoxPNfcAn5IPRgVU',
    appId: '1:863822323375:web:d89178dc4b0eeda0c23e5a',
    messagingSenderId: '863822323375',
    projectId: 'fir-setup-4d5ce',
    authDomain: 'fir-setup-4d5ce.firebaseapp.com',
    storageBucket: 'fir-setup-4d5ce.firebasestorage.app',
    measurementId: 'G-H1QTX2Y80W',
  );
}
